### ISSUE TITLE
Update of README file as it doesn't contain project admin information etc. 

### ISSUE THREAD

**Issue by Aditi-008** [visheshrwl/Uber-like#1]
I would like to add a project admin information section which will give the user full information about the project owner and help incase of issues to contact them. Kindly assign it to me under the label gssoc-ext and hacktoberfest-accepted along with the level of the problem.
Thank you!

**Comment by visheshrwl** [comment]
@Aditi-008 Feel free to proceed and if you need any additional info, reach out!!

**Comment by Aditi-008** [comment]
Sir would you like me to tell what all infos of yours are you ok with to be put up. Also if possible you can share any discord or other channel if you have. Basic information like name,mail id and linkedin I am working on it.

**Comment by visheshrwl** [comment]
https://linkedin.com/in/visheshrawal
