### ISSUE TITLE
Create a Dashboard for Real-Time Driver and Delivery Partner Tracking

### ISSUE THREAD

**Issue by visheshrwl** [visheshrwl/Uber-like#2]
**Describe the solution you'd like**
Build a dashboard view in the frontend to visualize the real-time locations of drivers and delivery partners using a map service (e.g., Mapbox or Google Maps API).

Steps:
1. Add a map component using a library like react-leaflet or react-google-maps.
2. Integrate real-time data from a backend endpoint (WebSocket or REST API).
3. Show markers for each driver/delivery partner and allow filtering by status.

**Comment by VertikaBajpai** [comment]
@visheshrwl  Please assign me this issue

**Comment by Prabhav444** [comment]
@visheshrwl please assign me this
