### ISSUE TITLE
Implement Health Check Endpoint for Backend Services

### ISSUE THREAD

**Issue by visheshrwl** [visheshrwl/Uber-like#3]
**Describe the solution you'd like**
Create a /health endpoint for each backend service (e.g., authentication, cab management, delivery management) that returns the health status, version, and uptime of the service.

Steps:
1. Create a new route /health in the respective service files.
2. Implement logic to check the status of the service and its dependencies (e.g., database, cache).
3. Return the health status in JSON format.

**Comment by abhishekpaturkar** [comment]
I want work on this issue. Please assign to me.

**Comment by visheshrwl** [comment]
# Health Check Implementation for Uber-Like Application

## Overview
The `/health` endpoint provides real-time status information of the service and its dependencies (e.g., databases, cache, message brokers), ensuring enhanced observability, automated failure detection, and integration with monitoring tools.

## Why Implement a `/health` Endpoint?
The `/health` endpoint is essential for monitoring the operational status of individual services in a microservices architecture. It offers multiple benefits, including:
- **Fault Detection:** Quickly identify and diagnose issues in any service or its dependencies.
- **Automated Rollbacks and Recovery:** Integrate with CI/CD pipelines to automatically revert deployments in case of unhealthy states.
- **Monitoring and Alerting:** Use the endpoint for real-time health checks with monitoring tools like Prometheus, Grafana, or AWS CloudWatch.
- **Scalability:** Enable auto-scaling mechanisms by tracking service health and resource utilization.

## Features of the `/health` Endpoint
Each service will implement a `/health` endpoint that provides the following information:
- **Overall Status:** Indicates whether the service is `healthy` or `unhealthy`.
- **Service Version:** Displays the current version of the service (extracted from the `package.json` or service configuration).
- **Uptime:** Shows the time (in seconds) since the service was started.
- **Dependency Status:** Reports the health of critical dependencies like:
  - **Database (e.g., PostgreSQL, MongoDB)**: Validates the connection and query execution.
  - **Cache (e.g., Redis)**: Checks if the cache is reachable and operational.
  - **Message Broker (e.g., Kafka)**: Ensures the producer and consumer clients are active.
