### ISSUE TITLE
Build Dashboard for Ride Requests

### ISSUE THREAD

**Issue by visheshrwl** [visheshrwl/Uber-like#38]
**Is your feature request related to a problem? Please describe.**
Create a dashboard that allows users to request rides, view available drivers, and track ride status.

**Additional context**

- Design the dashboard layout.
- Implement ride request form (pickup and drop locations).
- Show the nearest available drivers on the map (Google Maps API or Mapbox).
- Integrate with the backend API for ride requests.

**Comment by haseebzaki-07** [comment]
hey @visheshrwl I want to work on this issue
