### ISSUE TITLE
Implement Real-Time Location Tracking for Drivers

### ISSUE THREAD

**Issue by visheshrwl** [visheshrwl/Uber-like#39]
**Is your feature request related to a problem? Please describe.**
Display real-time driver location on the map for users waiting for their ride.

**Additional context**

- Set up WebSocket or GraphQL subscriptions for live updates.
- Integrate the map with real-time location data of the driver.
- Create an animated marker to show driver movement.

**Comment by haseebzaki-07** [comment]
hey @visheshrwl I want to work on this issue

**Comment by haseebzaki-07** [comment]
hey @visheshrwl you have not added the level and gssoc-ext tags on my previous PR #58 . please do so.

**Comment by haseebzaki-07** [comment]
hey @visheshrwl could you please add the levels in #58
