### ISSUE TITLE
Optimize and Scale Redis Caching Layer for Backend

### ISSUE THREAD

**Issue by visheshrwl** [visheshrwl/Uber-like#4]
**Describe the solution you'd like**
Improve the caching mechanism for frequently accessed data (e.g., active ride requests, partner availability) to handle high throughput and low latency requirements.

Steps:
1. Review existing caching mechanisms and identify bottlenecks.
2. Implement caching strategies like LFU (Least Frequently Used) or LRU (Least Recently Used).
3. Conduct performance benchmarking and include metrics.

**Comment by gaurkrutika** [comment]
Can you assign this to me? I would like to contribute

**Comment by haseebzaki-07** [comment]
hey @visheshrwl Can I take this issue
