### ISSUE TITLE
Payment Gateway Integration

### ISSUE THREAD

**Issue by visheshrwl** [visheshrwl/Uber-like#42]
**Is your feature request related to a problem? Please describe.**
Integrate a payment gateway for users to pay for their rides securely.

**Additional context**

- Design payment UI with options (credit card, PayPal, etc.).
- Integrate with Stripe, PayPal, or Razorpay APIs.
- Handle success and failure cases for payment transactions.

**Comment by haseebzaki-07** [comment]
hey @visheshrwl I want to work on this issue.
