### ISSUE TITLE
Integration of Advanced Routing Algorithms

### ISSUE THREAD

**Issue by visheshrwl** [visheshrwl/Uber-like#47]
**Is your feature request related to a problem? Please describe.**
Integrate advanced routing algorithms to optimize driver paths and reduce ride time.

**Additional context**
- Connect to backend routing API for optimized route suggestions.
- Update the UI to reflect real-time route changes.
- Show ETA and route details to the user.

**Comment by haseebzaki-07** [comment]
hey @visheshrwl I want to work on this issue!
