### ISSUE TITLE
[CI-CD] Set Up Automated Code Quality Checks with ESLint and Prettier

### ISSUE THREAD

**Issue by visheshrwl** [visheshrwl/Uber-like#6]
**Desired Behavior**
Integrate ESLint and Prettier into the CI/CD pipeline for consistent code quality and formatting checks across the codebase.

**Proposed Solution**
1. Add ESLint and Prettier configuration files.
2. Modify .github/workflows/ci-cd.yml to run ESLint and Prettier checks on each pull request.
3. Ensure that the pipeline fails if there are any code quality or formatting issues.

**Comment by Emilio-PdeA** [comment]
Hello @visheshrwl , can you assign me this task?

**Comment by visheshrwl** [comment]
@Emilio-PdeA amazing work.
Consider starring the repo and hoping for more PR's from your side.
