### ISSUE TITLE
Feature Request: Add Navbar with Route Navigation

### ISSUE THREAD

**Issue by sezallagwal** [visheshrwl/Uber-like#68]
## Description
Implement a navbar component to enhance navigation across the application. This navbar will provide users with quick access to all major routes, improving usability and allowing seamless movement between different sections of the site.

### Proposed Features
1. **Navbar Links** 
- add all the routes link to navbar

3. **Responsive Design**
   - Ensure the navbar is responsive and user-friendly on both desktop and mobile views.
   - For mobile, consider implementing a hamburger menu to save screen space.

4. **Active Link Highlighting**
   - Highlight the active route link in the navbar to indicate the current page.
   
5. **Conditional Rendering**
   - Show or hide certain links based on user authentication or role, if applicable.

### Expected Outcome
With this navbar, users will be able to navigate between different routes effortlessly, enhancing the user experience and accessibility of the application.

---

Please assign this issue under the `gssoc-ext` and `hacktoberfest` labels.

**Comment by visheshrwl** [comment]
Hey @sezallagwal ! 👋

First off, I want to extend a huge thank you to all of you for your amazing contributions to this project! Your support and hard work mean a lot, and I truly appreciate everything you do. 🙏

I have a small favor to ask: if you think I’ve been helpful and supportive throughout your contributions, I would be honored if you could nominate me by filling out this form: [Nominate me](https://docs.google.com/forms/d/e/1FAIpQLSdnqJ5crpQFQEQXGTzekfKUxOJCXkSx8AykqvvHzlqBcNGMAQ/viewform).

Your nomination would mean the world to me, and it’s a great way to help me continue supporting our awesome community. Thanks again for all the amazing work, and let's keep making great things happen! 🚀

Best,
Vishesh
