### ISSUE TITLE
Add GitHub Workflows for Greetings, Auto-Labeling, and PR Merge Notifications

### ISSUE THREAD

**Issue by samyak-aditya** [visheshrwl/Uber-like#74]
**Description:**
To enhance repository automation and streamline contributor engagement, let's add GitHub workflows for greeting new contributors, auto-labeling pull requests, and notifying contributors on successful PR merges.

**Proposed Workflows:**
1. **Greetings Workflow:** Automatically welcome new contributors with a personalized message on their first issue or PR, encouraging them to contribute further.
2. **Auto-Labeling Workflow:** Configure a workflow to apply labels based on PR or issue content, making it easier to categorize and manage tasks.
3. **PR Merge Notification:** Add a workflow to send a notification to contributors when a pull request is successfully merged, keeping them informed of project updates.

**Benefits:**
These workflows will improve contributor experience, enhance project organization, and ensure that all contributors stay informed, contributing to a smoother collaboration process.

hey @visheshrwl Please assign me this Task

**Comment by samyak-aditya** [comment]
Hey @visheshrwl Is there any possiblity that you could assign it level3
coz
- I will improve the greetings workflow to include the name of the issue opener
- add a auto label workflow
-  add a workflow to alert the pr owners when their PR are merged with 

Do let me know what you think
Thanks for assigning me this task 💯

**Comment by visheshrwl** [comment]
Hey @samyak-aditya , Thanks for your enthusiasm! I’ve kept this at level 2 because while these are great enhancements, they fall under workflow automation and notification setup, which are relatively scoped and straightforward. Level 3 typically requires a more complex design, multi-system integration, or deeper architectural changes. Looking forward to seeing these improvements in action—thanks again for the initiative!

**Comment by samyak-aditya** [comment]
Hey @visheshrwl Ok understood 
Thanks for Explaning keep up the good work
Amazing project btw

**Comment by samyak-aditya** [comment]
Hey @visheshrwl I have raised the PR
