### ISSUE TITLE
[CI-CD] Implement Canary Releases in CI/CD Pipeline using Argo Rollouts

### ISSUE THREAD

**Issue by visheshrwl** [visheshrwl/Uber-like#8]
**Desired Behavior**
Enhance the CI/CD pipeline with canary releases using Argo Rollouts to enable gradual traffic shifting and automated rollback in case of failure.

**Proposed Solution**
1. Install and configure Argo Rollouts in the Kubernetes cluster.
2. Update deployment.yaml files to include Argo Rollout strategies.
3. Add logic to handle automatic rollback based on metrics (e.g., error rate, latency).

**Comment by Aryam2121** [comment]
close this i am completed this
