### ISSUE TITLE
[ALGORITHM] Routing Algorithm to Include Real-Time Traffic Data

### ISSUE THREAD

**Issue by visheshrwl** [visheshrwl/Uber-like#9]
**Proposed Improvement**
Include real-time traffic data using APIs like Google Maps Traffic or TomTom Traffic API to ensure optimal route selection.

**Implementation Details**
1. Integrate with a real-time traffic data provider.
2. Modify the routing algorithm to factor in current traffic conditions.
3. Validate results with test cases and real-world scenarios.

**Comment by Aryam2121** [comment]
I SOLVED THAT ISSUE

**Comment by Aryam2121** [comment]
but in my Hacktober fest it show it 2 pr in review why??
